package uk.co.aosd.flash.dto;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.List;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import uk.co.aosd.flash.domain.SaleStatus;

/**
 * DTO for creating a new Flash Sale.
 */
@Schema(
    name = "CreateFlashSale",
    description = "Request body for creating a new flash sale (admin API)."
)
public record CreateSaleDto(
    @Schema(
        description = "Flash sale identifier. Typically generated by the system.",
        example = "5b3c3f18-2f88-4c38-8b35-9aa6d9b9f5af"
    )
    String id,
    @Schema(description = "Flash sale title.", example = "Winter Deals")
    @NotEmpty(message = "A non-empty title is needed for the sale.") String title,
    @Schema(description = "Sale start time (ISO-8601).", example = "2026-02-01T09:00:00Z")
    @NotNull(message = "The sale needs a valid start time.") OffsetDateTime startTime,
    @Schema(description = "Sale end time (ISO-8601).", example = "2026-02-01T12:00:00Z")
    @NotNull(message = "The sale needs a valid end time.") OffsetDateTime endTime,
    @Schema(description = "Initial sale status.", example = "DRAFT")
    @NotNull(message = "The sale needs a valid status.") SaleStatus status,
    @Schema(description = "Products to include in the sale, with reserved allocations.")
    @Valid @NotEmpty(message = "The sale needs at least one product.") List<SaleProductDto> products
) implements Serializable {
}
