package uk.co.aosd.flash.dto;

import java.io.Serializable;
import java.math.BigDecimal;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotEmpty;

/**
 * A Product DTO.
 */
@Schema(
    name = "Product",
    description = "Product managed by the admin service."
)
public record ProductDto(
    @Schema(
        description = "Product identifier. Typically generated by the system.",
        example = "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    )
    String id,
    @Schema(description = "Product name.", example = "Wireless Mouse")
    @NotEmpty(message = "A name must be provided.") String name,
    @Schema(description = "Product description.", example = "Ergonomic wireless mouse with USB-C charging.")
    @NotEmpty(message = "A description must be provided.") String description,
    @Schema(description = "Total physical stock available for this product.", example = "100")
    @Min(value = 0, message = "Stock cannot be negative") Integer totalPhysicalStock,
    @Schema(description = "Base price (non-sale price).", example = "29.99")
    @Min(value = 0, message = "Price cannot be negative") BigDecimal basePrice,
    @Schema(description = "Quantity currently reserved for upcoming/active sales.", example = "10")
    @Min(value = 0, message = "ReservedCount cannot be negative") Integer reservedCount)
    implements Serializable {
}
